name: Car Alert Bot

on:
  schedule:
    - cron: "0 14 * * *"  # 14:00 UTC (9:00 AM Central)
  workflow_dispatch:

jobs:
  run-car-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Start Xvfb (Virtual Display)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        shell: bash

      - name: Run car scraper script
        env:
          DISPLAY: :99
          TELEGRAM_TOKEN_1: ${{ secrets.TELEGRAM_TOKEN_1 }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LOCAL_PLACE_NAME: ${{ secrets.LOCAL_PLACE_NAME }}
        run: |
          python car_scraper.py