name: Car Alert Bot

on:
  schedule:
    - cron: "0 14 * * *"  # 14:00 UTC (9:00 AM Central)
  workflow_dispatch:

jobs:
  run-car-scraper:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            unzip \
            xvfb \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxss1 \
            libasound2 \
            libgbm-dev

      - name: Install Chromium and chromedriver
        run: |
          sudo apt-get install -y chromium-browser
          wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp/chromedriver
          sudo mv /tmp/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run car scraper script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_1 }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LOCAL_PLACE_NAME: ${{ secrets.LOCAL_PLACE_NAME }}
        run: |
          python car_scraper.py
