name: Car Alert Bot

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  run-car-scraper:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 \
            libappindicator1 libindicator7 libgbm1 libnss3 fonts-liberation \
            xdg-utils libu2f-udev libvulkan1 chromium-driver google-chrome-stable

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run car scraper script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_1 }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LOCAL_PLACE_NAME: ${{ secrets.LOCAL_PLACE_NAME }}
        run: |
          python car_scraper.py